# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IK0d7bBVx5LtcOCu10vyTb65RadRakgq
"""

def calculator():
    print("Simple Calculator")
    print("Operations: +  -  *  /")

    num1 = float(input("Enter first number: "))
    operator = input("Enter operator (+, -, *, /): ")
    num2 = float(input("Enter second number: "))

    match operator:
        case "+":
            print("Result:", num1 + num2)
        case "-":
            print("Result:", num1 - num2)
        case "*":
            print("Result:", num1 * num2)
        case "/":
            if num2 != 0:
                print("Result:", num1 / num2)
            else:
                print("Error: Division by zero!")
        case _:
            print("Invalid operator!")

calculator()